/* eslint-disable no-unused-vars */
/* ...params are used */
import { RouteLink } from "../../core/Router/router.d";
import { IPageConfigs } from "../../pages/page.d";
import { IComponentFactory } from "../../services/factory/factory.d";
import { TagNames } from "../../services/render/DOM/DOM.d";
import FragmentService from "../../services/render/Fragment/FragmentService.ts";
import Component from "./Component.ts";

/**
 * Defines the fundamental public contract for a Component's properties.
 * Public-facing API of a Component instance.
 */
export interface BaseProps {
  configs: IComponentConfigs;
  attributes?: IComponentAttributes;
  events?: IComponentEvents;
  childrenData?: IChildrenData;
}

/* Dependency Injection services */
export interface IComponentDeps {
  domService: DOMService;
  fragmentService: FragmentService;
}

/* Data for a concrete Component instance */
export interface IComponentData<TProps extends BaseProps = BaseProps> {
  /* Non-attributes configurations, {{}} */
  configs: TProps["configs"];
  attributes?: TProps["attributes"];
  events?: TProps["events"];
  childrenData?: TProps["childrenData"];
  componentFactory: IComponentFactory<TProps>;
  /* children is generated by the factory, if it's not defined */
  children?: IChildren<TProps>;
}

/* Configuration data for a concrete Component instance */
export interface IComponentConfigs {
  /* slotKey resembles the hbs {{{html-escaping expressions}}} */
  slotKey: string;
  tagName: TagNames;
  type?: string | RouteLink;
  pageConfigs?: IPageConfigs;
}

/* Attributes for root tag of a Component */
export interface IComponentAttributes {
  className?: string;
  type?: string;
  style?: string;
  for?: string;
}

/* Event handlers for a concrete Component instance */
export type IComponentEvents = Record<string, (event: Event) => void>;

/**
 * No extenstions here, because IChildrenData is general abstract Component
 * For conctrete Components types, look at each children interfaces in the pages
 */

export type IChildrenData = Record<
  string,
  /* IComponentData<BaseProps> Represents the data for ANY valid component. */
  | { type: "single"; data: IComponentData<BaseProps> }
  | {
      type: "list";
      slotKey: string;
      dataList: readonly IComponentData<BaseProps>[];
      childrenFactory: IComponentFactory<BaseProps>;
    }
>;

/**
 * It's a proptery/state of the Component.
 */
export type IChildren = Record<
  string,
  | { type: "single"; child: Component<BaseProps> }
  | {
      type: "list";
      slotKey: string;
      children: Component<BaseProps>[];
      childrenFactory: IComponentFactory<BaseProps>;
    }
>;

export interface IChildrenList {
  slotKey: string;
  list: Component<BaseProps>[];
  componentFactory: IComponentFactory<BaseProps>;
}
