/* eslint-disable no-unused-vars */
/* ...params are used */
import { RouteLink } from "../../core/Router/router.d";
import { IPageConfigs } from "../../pages/page.d";
import { TagNames } from "../../services/render/DOM/DOM.d";
import FragmentService from "../../services/render/Fragment/FragmentService.ts";
import Component from "./Component.ts";

/**
 * Defines the fundamental public contract for a Component's properties.
 * Public-facing API of a Component instance.
 */
export interface BaseProps {
  configs: IComponentConfigs;
  attributes?: IComponentAttributes;
  events?: IComponentEvents;
  childrenData?: IChildrenData;
}

/* Dependency Injection services */
export interface IComponentDeps {
  domService: DOMService;
  fragmentService: FragmentService;
}

/* Data for a concrete Component instance */
export interface IComponentData {
  /* Non-attributes configurations, {{}} */
  configs: BaseProps["configs"];
  attributes?: BaseProps["attributes"];
  events?: BaseProps["events"];
  childrenData?: BaseProps["childrenData"];
  componentFactory: IComponentFactory<BaseProps>;
  /* children is generated by the factory */
  children?: IChildren;
}

/* Configuration data for a concrete Component instance */
export interface IComponentConfigs {
  /* slotKey resembles the hbs {{{html-escaping expressions}}} */
  slotKey: string;
  tagName: TagNames;
  type?: string | RouteLink;
  pageConfigs?: IPageConfigs;
}

/* Attributes for root tag of a Component */
export interface IComponentAttributes {
  className?: string;
  type?: string;
  style?: string;
}

/* Event handlers for a concrete Component instance */
export type IComponentEvents = Record<string, (event: Event) => void>;

/**
 * No extenstions here, because IChildrenData is general abstract Component
 * For conctrete Components types, look at each children interfaces in the pages
 */
export type IChildrenData <TProps extends BaseProps> = Record<
  string,
  | { type: "single"; data: IComponentData<TProps> }
  | {
      type: "list";
      listKey: string;
      dataList: IComponentData<TProps>[];
      childrenFactory: IComponentFactory<TProps>;
    }
>;

/**
 * It's a proptery/state of the Component.
 */
export type IChildren = Record<
  string,
  | { type: "single"; child: Component<BaseProps> }
  | {
      type: "list";
      listKey: string;
      children: Component<BaseProps>[];
      childrenFactory: IComponentFactory<BaseProps>;
    }
>;

export interface IChildrenList {
  slotKey: string;
  list: Component<BaseProps>[];
  componentFactory: IComponentFactory<BaseProps>;
}

export type IComponentFactory<TProps extends BaseProps> = (
  data: ComponentParams<TProps>,
) => Component<TProps>;
