/* eslint-disable no-unused-vars */
/* ...params are used */
import { IPageConfigs } from "../../pages/page.d";
import { TagNames } from "../../services/render/DOM/DOM.d";
import FragmentService from "../../services/render/Fragment/FragmentService.ts";
import { IComponentFactory } from "../../utils/factory/factory.d";
import { ChildrenPropsMap, IChildren, IChildrenData } from "./Children.d";

/**
 * Defines the fundamental public contract for a Component's properties.
 * Public-facing API of a Component instance.
 */
export interface BaseProps {
  configs: IComponentConfigs;
  attributes?: IComponentAttributes;
  events?: IComponentEvents;
  childrenData?: IChildrenData;
}

/* Dependency Injection services */
export interface IComponentDeps {
  domService: DOMService;
  fragmentService: FragmentService;
}

/* Data for a concrete Component instance */
export interface IComponentData<TProps extends BaseProps = BaseProps> {
  /* Non-attributes configurations, {{}} */
  configs: TProps["configs"];
  attributes?: TProps["attributes"];
  events?: TProps["events"];
  childrenData?: TProps["childrenData"];
  componentFactory: IComponentFactory<TProps>;
  /* children is generated by the factory, if it's not defined */
  children?: IChildren<ChildrenPropsMap>;
  /* page-specific configs */
  pageConfigs?: IPageConfigs;
}

/* Configuration data for a concrete Component instance */
export interface IComponentConfigs {
  /* slotKey resembles the hbs {{{html-escaping expressions}}} */
  slotKey: string;
  tagName: TagNames;
  type?: string;
  pageConfigs?: IPageConfigs;
}

/* Attributes for root tag of a Component */
export interface IComponentAttributes {
  className?: string;
  type?: string;
  style?: string;
  for?: string;
}

/* Event handlers for a concrete Component instance */
export type IComponentEvents = Record<string, (event: Event) => void>;
