/* eslint-disable no-unused-vars */
/* ...params are used */
import { PageConfigs } from "../../pages/page.d";
import { TagNameType } from "../../services/render/DOM/dom.d";
import FragmentService from "../../services/render/Fragment/FragmentService.ts";
import { ComponentFactory } from "../../utils/factory/factory.d";
import { ChildrenPropsMap, Children, ChildrenData } from "./children.d";

/**
 * Defines the fundamental public contract for a Component's properties.
 * Public-facing API of a Component instance.
 */
export interface BaseProps {
  configs: ComponentConfigs;
  attributes?: ComponentAttributes;
  events?: ComponentEvents;
  childrenData?: ChildrenData;
}

/* Dependency Injection services */
export interface ComponentDeps {
  domService: DOMService;
  fragmentService: FragmentService;
}

/* Data for a concrete Component instance */
export interface ComponentData<TProps extends BaseProps = BaseProps> {
  /* Non-attributes configurations, {{}} */
  configs: TProps["configs"];
  attributes?: TProps["attributes"];
  events?: TProps["events"];
  childrenData?: TProps["childrenData"];
  componentFactory: ComponentFactory<TProps>;
  /* children is generated by the factory, if it's not defined */
  children?: Children<ChildrenPropsMap>;
  /* page-specific configs */
  pageConfigs?: PageConfigs;
  /* store-props */
  storeProps?: Record<string, unknown>;
}

/* Configuration data for a concrete Component instance */
export interface ComponentConfigs {
  /* slotKey resembles the hbs {{{html-escaping expressions}}} */
  slotKey: string;
  tagName: TagNameType;
  type?: string;
  pageConfigs?: PageConfigs;
}

/* Attributes for root tag of a Component */
export interface ComponentAttributes {
  className?: string;
  type?: string;
  style?: string;
  for?: string;
}

/* Event handlers for a concrete Component instance */
export type ComponentEvents = Record<string, (event: Event) => void>;

export type ComponentEventBusEvents =
  | "init" // Component initialized
  | "flow:component-did-mount" // Component added to DOM
  | "flow:render" // Component rendered
  | "flow:component-did-update" // Component updated
  | "flow:component-did-unmount"; // Component unmounted
